apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: linkerd
    git:
      url: https://github.com/giantswarm/linkerd2-upstream
      ref: stable-2.13.x
    includePaths:
    - charts/linkerd2-cni/**/*
    - charts/partials/**/*
- path: helm/linkerd2-cni/templates
  contents:
  - path: .
    directory:
      path: vendor/linkerd/charts/linkerd2-cni/templates
- path: helm/linkerd2-cni/charts/partials
  contents:
  - path: .
    directory:
      path: vendor/linkerd/charts/partials
