checks:
  addAllBuiltIn: true
  exclude:
  - "host-network"
  - "no-liveness-probe"
  - "no-readiness-probe"
  - "required-annotation-email"
  - "required-label-owner"
  - "run-as-non-root"
  - "writable-host-mount"
