apiVersion: v1
appVersion: 0.0.1
description: A helm chart containing the resources needed by the Linkerd CNI plugin.
engine: gotpl
home: https://github.com/giantswarm/linkerd2-cni-app
icon: https://s.giantswarm.io/app-icons/1/png/linkerd2-app-light.png
kubeVersion: '>=1.13.0-0'
maintainers:
- email: cncf-linkerd-dev@lists.cncf.io
  name: Linkerd authors
  url: https://linkerd.io/
- name: Giant Swarm applications team
  url: https://github.com/giantswarm/linkerd2-cni-app
name: linkerd2-cni-app
sources:
- https://github.com/linkerd/linkerd2
- https://github.com/giantswarm/linkerd2-cni-app
version: [[ .Version ]]
