apiVersion: v1
appVersion: 2.11.2
description: |
  Linkerd is a *service mesh*, designed to give platform-wide observability,
  reliability, and security without requiring configuration or code changes. The
  Linkerd [CNI plugin](https://linkerd.io/2/features/cni/) takes care of setting
  up your pod's network so  incoming and outgoing traffic is proxied through the
  data plane.
engine: gotpl
home: https://github.com/giantswarm/linkerd2-cni-app
icon: https://s.giantswarm.io/app-icons/1/png/linkerd2-app-light.png
kubeVersion: ">=1.17.0-0"
annotations:
  application.giantswarm.io/team: team-cabbage
maintainers:
- email: cncf-linkerd-dev@lists.cncf.io
  name: Linkerd authors
  url: https://linkerd.io/
- name: Giant Swarm applications team
  url: https://github.com/giantswarm/linkerd2-cni-app
name: linkerd2-cni-app
sources:
- https://github.com/linkerd/linkerd2
- https://github.com/giantswarm/linkerd2-cni-app
version: 0.4.0
restrictions:
  clusterSingleton: true
  fixedNamespace: linkerd-cni
