apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook-weight": "-1"
    {{- include "jobAnnotations" . | nindent 4 }}
  labels:
    {{- include "jobLabels" . | nindent 4 }}
spec:
  privileged: false
  runAsUser:
    rule: 'MustRunAs'
    ranges:
      - min: {{ .Values.userID }}
        max: {{ .Values.userID }}
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: {{ .Values.userID }}
        max: {{ .Values.userID }}
  volumes:
  - 'secret'
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: {{ .Values.groupID }}
        max: {{ .Values.groupID }}
  readOnlyRootFilesystem: true
