apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-1"
    {{- include "jobAnnotations" . | nindent 4 }}
  labels:
    {{- include "jobLabels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  resourceNames:
  - {{ .Release.Namespace }}
  verbs:
  - "get"
  - "list"
  - "patch"
  - "update"
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.name }}
  verbs:
  - "use"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-2"
    {{- include "jobAnnotations" . | nindent 4 }}
  labels:
    {{- include "jobLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Release.Namespace }}
