apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook-weight": "-1"
    {{- include "jobAnnotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jobLabels" . | nindent 4 }}
